### PR TITLE
Enhance test-suite

### PR DESCRIPTION
**Pull request by tvdijen**

### CODE REVIEW

**Comment by tvdijen** [comment]
@sgomez I'm not familiar with `phpspec`.. Is this something that needs to be kept?

**Comment by sgomez** [comment]
Thanks @tvdijen. If you don't want, you don't need to correct the code, it's a lot of work and I can do it. Especially because there are old libraries that I want to replace (zend-diactoros) and I don't want to waste your time.

Anyway, I did not to add the @inheritdoc in some classes than extends from third-party libraries. This will add type hinting in some places that will broke the tests.

**Comment by tvdijen** [comment]
Oh that's okay, I really don't mind doing it.. It may be helpful to have your tests pass 100% before you start working on library replacements..
It's probably a good idea if I split the PR into three (testsuite, phpdoc, typehints) to not blow this one up..

**Comment by tvdijen** [comment]
@sgomez I've split the PR into two for now.. If you could merge the PHPdoc-PR, I can rebase this one and see what's left to fix without doing too much on the old Zend-code

**Comment by sgomez** [comment]
Done @tvdijen.

**Comment by tvdijen** [comment]
> 
> 
> Done @tvdijen.

Great, but you may have been a little bit too quick..
It had a syntax error, so maybe you want to cherry-pick https://github.com/rediris-es/simplesamlphp-module-oidc/pull/31/commits/f323f1631aaa1081692416131765b3b425ef54d3
It is also part of this PR right now...

**Comment by tvdijen** [comment]
I'm happy with it.. Tests pass except for Psalm

**Comment by sgomez** [comment]
Thanks @tvdijen !

**Pull request merged**
